version: '3.8'

services:
  aggregator:
    image: python:3.9.15-slim-bullseye
    volumes:
      - ../..:/app
    command: sleep infinity

  db:
    image: mariadb:10.9.4-jammy
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example

  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - 8080:8080
